# Generated by Django 3.1.3 on 2021-04-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='dr_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialist', models.CharField(max_length=30)),
                ('hospital', models.CharField(max_length=30)),
                ('consultation_period', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('fee', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.login')),
            ],
        ),
    ]
